name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

env:
  JAVA_VERSION: 17
  JAVA_DISTRIBUTION: temurin
  GRADLE_VERSION: 7.5

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Run linter
        run: ./gradlew ktlintCheck

      - name: Upload ktlint report
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path: build/reports/ktlint

  test:
    name: 'Test'
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ env.GRADLE_VERSION }}

      - name: Run test suite
        run: ./gradlew test

      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: |
            build/reports/tests/test
            build/reports/jacoco/test
